trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  - group: 'DockerHub'
  - name: 'imageName' 
    value: 'livingdevops/$(Build.Repository.Name):$(Build.SourceBranchName)'

steps:
- script: docker login -u $(user) -p $(password)
  displayName: 'docker login'

- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'

- script: docker push $(imageName)
  displayName: 'docker push'
