
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  - group: 'DockerHub'
  - name: imageName 
    value: 'livingdevops/lidop.ssh-slave-docker:latest'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  enabled: false
  displayName: 'docker build'

- script: docker login -u $(user) -p $(password)
  displayName: 'docker build'
