trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  - group: 'DockerHub'
  - name: 'imageName' 
    value: '$(Build.Repository.Name):latest$(Build.SourceBranchName)'

steps:
- script: |
    export imageName=$(echo "$(imageName)" | sed -e 's/master/latest/g')
    echo '##vso[task.setvariable variable=imageName]$(imageName)'
    echo "ImageName: $(imageName)"
  displayName: 'set variables'

- script: docker login -u $(user) -p $(password)
  displayName: 'docker login'

- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'

- script: docker push $(imageName)
  displayName: 'docker push'
